@startuml
scale 1.5
left to right direction
skinparam packageStyle rect
actor "Developer" as dev
actor "Player" as user
rectangle "Map System" as system {
  rectangle "Map Generator" as mapgen {
    (Set TileSet Height/Width) as (tileSetSize)
    (Set Tile Sprites) as (setMapSprite)
    (Set Isometric/2D Mode) as (toggleIsometric)
    (Set Sprite Size) as (setSpriteSize)
    (Set Max Straight Line Length) as (setMaxStraightness)
    note "These values are set in the inspector of Unity" as note1
    (Generate Map) as (genMap)
    (Expand Map) as (expandMap)
    note "Internally instantiates GameObjects to draw the map" as drawMap
    (Validate Expandability) as (validateExpansion)
    (Call TileSet Generator to Generate Map Portion) as (callTileSet)
  }

  rectangle "TileSet Generator" as tileset {
    (Generate TileSet) as (genTileSet)
    (Generate Path) as (genPath)
  }

  (setMapSprite) --> note1
  (toggleIsometric) --> note1
  (setSpriteSize) --> note1
  (setMaxStraightness) --> note1
  (genMap) --> (drawMap)
  (expandMap) --> (drawMap)
  (expandMap)..> (validateExpansion): <<include>>
  (validateExpansion)..> (callTileSet): <<include>>
  (genMap)..> (callTileSet): <<include>>
  (tileSetSize)<.. (callTileSet): <<include>>

  (callTileSet)..> (genTileSet): <<include>>
  (genTileSet)..> (genPath): <<include>>

  user -- (genMap)
  user -- (expandMap)

  dev -- (tileSetSize)
  dev -- (setMapSprite)
  dev -- (toggleIsometric)
  dev -- (setSpriteSize)
  dev -- (setMaxStraightness)
  dev -- (genMap)
  dev -- (expandMap)
}
@enduml